### ISSUE TITLE
Questions about isaac sim environment configuration issues and how to read the framework

### ISSUE THREAD

**Issue by Seas00n** [silvery107/rl-mpc-locomotion#11]
Hello, I would like to ask if you can participate in this project if you can successfully install Isaac gym but cannot run Isaac sim correctly. Isaac Sim prompts that the graphics card cannot be found, but I made sure to install the relevant driver myself.
In addition, I would like to ask if there is terrain information such as scanning point data in the framework that participates in the training. If so, where should I start to learn the status configuration of the environment information?

**Comment by silvery107** [comment]
Hi, thanks for your interests in my project.

I don't understand the first part of your question, and this project has nothing to do with Isaac Sim basically. If there is a specific driver side error, please check driver support instead.

Regarding height sampling of terrain, you could check the [implementation ](https://github.com/leggedrobotics/legged_gym/blob/master/legged_gym/envs/base/legged_robot.py#L777-L789) of `get_height()` function of legged_gym.
