### ISSUE TITLE
About how to deploy this controller to the robot I built.

### ISSUE THREAD

**Issue by jiangtaohu1206** [silvery107/rl-mpc-locomotion#12]
Thank you very much for your sharing, which gives me a lot of inspiration. 
I want to deploy this controller on the robot I built later. Could you recommend a real robot deployment scheme for reference?
Thanks a lot.

**Comment by silvery107** [comment]
Hi, if you are building a custom quadruped robot, try start with replacing one of the current URDF with your robot and tuning its corresponding parameters (kinematics, controller...).
