### ISSUE TITLE
Hello, I'd like to ask how the reward function in the code is designed, referring to the thesis?

### ISSUE THREAD

**Issue by chendayuxixi** [silvery107/rl-mpc-locomotion#14]
thank you very much!

**Comment by silvery107** [comment]
Hi, thanks for your interests.

The reward design are mainly refered to [this paper](https://arxiv.org/abs/2109.11978), and you can also find more details in [my slides](https://docs.google.com/presentation/d/18bznpYrkCPnhCisySPDz18hvL3Ytere7JiJEbdLvpgU/edit?usp=sharing). Specific rewards are defined in [task config files](https://github.com/silvery107/rl-mpc-locomotion/tree/main/RL_Environment/cfg/task), and computed in [this function](https://github.com/silvery107/rl-mpc-locomotion/blob/main/RL_Environment/tasks/aliengo.py#L358-L407) for each environment.
