### ISSUE TITLE
why  you  set      stiffness=0  damping =0 in config ?

### ISSUE THREAD

**Issue by heartInsert** [silvery107/rl-mpc-locomotion#15]
Hi ,  bro .  Recently  I  am  trying to  train  a  PPO  policy  in  Isaacgym  and  deploy  to  AliengoRobot ,  but  I    see  your   stiffness=0  damping =0  ,    how  can  you  control  your  robot  to  move ?

**Comment by silvery107** [comment]
Hi,

Joint stiffness and damping are actually simulated by the actuator, so by setting them to zero means we hand over the control authority to joint controller, and stiffness and damping are simulated [there](https://github.com/silvery107/rl-mpc-locomotion/blob/main/MPC_Controller/common/LegController.py#L125-L127) by computing PD feedback torques.

Thanks.
