### ISSUE TITLE
not using the Xbox-like but keyboard

### ISSUE THREAD

**Issue by ghost** [silvery107/rl-mpc-locomotion#21]
how to solve the problem

**Comment by silvery107** [comment]
You can check `gamepad_reader.py` and use the same library to read your keyboard inputs and map to corresponding commands.

Welcome to open a PR for that once you solve it!

**Comment by ghost** [comment]
As you say, I check gamepad_reader.py and use the same lib to read my keyboard inputs, but it cant not map to corresponding commands. I am sure read my keyboard inputs successfully but can not control the robot in sim. Just modifying codes in gamepad_reader.py?

**Comment by silvery107** [comment]
Could you be more specific by "it cant not map to corresponding commands"? What fields did you fill in with the keyboard inputs in`gamepad_reader.py` and what's the entry script of your "robot in sim" (like `RL_MPC_Locomotion.py`)?

**Comment by silvery107** [comment]
Close due to inactivity.

**Comment by silvery107** [comment]
Close due to inactivity.
