### ISSUE TITLE
How to achieve forward, backward, left, and right movement of the robot?

### ISSUE THREAD

**Issue by zhagao380** [silvery107/rl-mpc-locomotion#24]
After executing this command：python RL_MPC_Locomotion.py --robot=Aliengo".Opened Isaac Gym to control the robot with a joystick, only the LB and RB buttons are responsive. How can I achieve forward, backward, left, and right movement of the robot?"

**Comment by silvery107** [comment]
Hi,

After launching the GUI, press `RB` once to switch the state machine into locomotion mode and you should see the robot starts trotting. 

In locomotion mode, use left joystick to move and right joystick to rotate. If the robot is not responding, check the readings of your gamepad in `RL_Environment/gamepad_reader.py`. 

It may be the case that your gamepad is not supported by that library.
