### ISSUE TITLE
The version eigen3@02f4200 is no longer available

### ISSUE THREAD

**Issue by ling-1226** [silvery107/rl-mpc-locomotion#28]
The version eigen3@02f4200 is no longer available.Is there a specific reason why this commit must be used, or can other versions of Eigen be used instead?

**Comment by silvery107** [comment]
Interesting. And yes you should be able to compile with other versions of eigen3. If you did success, please feel free to report the version you chose here.

**Comment by ling-1226** [comment]
Thank you.I used version 3.3.7 of this link(https://github.com/eigenteam/eigen-git-mirror/tags) to successfully compile.Is there no gamepad to run this project?

**Comment by silvery107** [comment]
Try append `--disable-gamepad --mode=Min` and edit `commands` in the entry script.
