### ISSUE TITLE
Sim2Real in Go1

### ISSUE THREAD

**Issue by Kwon-nahyun** [silvery107/rl-mpc-locomotion#9]
I am trying to do sim2real on Go1 based on your code. 
In your code, controller_dt = 0.01 # in sec, but I am curious whether controller_dt was set to 0.01 in the actual robot.

**Comment by silvery107** [comment]
Thanks for your interests.

The controller is running at 200 Hz while the mpc solver is running at 40 Hz on real robot.

**Comment by Kwon-nahyun** [comment]
Thanks to you, I was able to successfully run sim2real on unitree go1. thank you.

**Comment by silvery107** [comment]
Congrats! Would you like to contribute to this repo regarding the sim2real transfer?
